name: Deploy Full Stack Application

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'data/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # This job runs first to determine which parts of the app have changed.
  check-changes:
    name: Check for File Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'data/**'
            frontend:
              - 'frontend/**'

  # Job to deploy the backend infrastructure
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: check-changes
    # This job only runs if the 'backend' filter is true.
    if: needs.check-changes.outputs.backend == 'true'
    outputs:
      api_url: ${{ steps.get_outputs.outputs.api_url }}
      table_name: ${{ steps.get_outputs.outputs.table_name }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      - name: Terraform Init, Plan, and Apply
        working-directory: ./backend/environments/dev
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
      - name: Get Terraform Outputs
        id: get_outputs
        working-directory: ./backend/environments/dev
        run: |
          API_URL=$(terraform output -raw api_invoke_url)
          TABLE_NAME=$(terraform output -raw dynamodb_table_name)
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "table_name=$TABLE_NAME" >> $GITHUB_OUTPUT
      - name: Seed DynamoDB Table
        env:
          TABLE_NAME: ${{ steps.get_outputs.outputs.table_name }}
        run: |
          chmod +x ./data/seed_database.sh
          ./data/seed_database.sh "$TABLE_NAME"

  # Job to deploy the frontend application
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [check-changes, deploy-backend]
    # This job runs if the 'frontend' filter is true OR if the backend job just ran successfully.
    if: |
      always() && (
        needs.check-changes.outputs.frontend == 'true' ||
        needs.deploy-backend.result == 'success'
      )
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::456202167790:role/githubaction
          aws-region: us-east-1
          
      - name: Look up Amplify App ID
        id: lookup_app_id
        run: |
          APP_ID=$(aws amplify list-apps | jq -r '.apps[] | select(.name == "Project-9-intermediate-level-Cloud-Dictionary-App") | .appId')
          echo "app_id=$APP_ID" >> $GITHUB_OUTPUT
          
      - name: Update Amplify Environment and Trigger Build
        env:
          # Use the backend URL if that job ran, otherwise, this will be empty and no update will happen.
          API_URL: ${{ needs.deploy-backend.outputs.api_url }}
          APP_ID: ${{ steps.lookup_app_id.outputs.app_id }}
        run: |
          # Only update environment variables if a new API_URL was provided
          if [ -n "$API_URL" ]; then
            echo "Updating Amplify App ID: $APP_ID with URL: $API_URL"
            aws amplify update-app --app-id "$APP_ID" --environment-variables "VITE_API_URL=$API_URL"
          else
            echo "No backend changes. Skipping environment variable update."
          fi
          
          echo "Starting new build for Amplify App ID: $APP_ID"
          aws amplify start-job --app-id "$APP_ID" --branch-name main --job-type 'RELEASE'